---
title: "Data Cleaning"
format: html
editor: visual
---

```{r import data, include=FALSE}
library(readxl)

estimanddb <- read_xlsx("Morgaine Data Cleaning.xlsx")
```

```{r check for missing in all fields required for cleaning, include=TRUE}

#NCT Number missing values:

print("Count of total missing values")
sum(is.na(estimanddb$`NCT number (if available)`))
print("Position of missing values ")
which(is.na(estimanddb$`NCT number (if available)`))

# "Count of total missing values"
# 1
# "Position of missing values "
# 1986

#Does not appear to have NCT number, use "Nil known" for NCT Number field in row 1986.

estimanddb$`NCT number (if available)`[is.na(estimanddb$`NCT number (if available)`)] <- "Nil known"

print("Count of total missing values")
sum(is.na(estimanddb$`NCT number (if available)`))
print("Position of missing values ")
which(is.na(estimanddb$`NCT number (if available)`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

##################################################################################################################################

#ISRCTN Number missing values:

print("Count of total missing values")
sum(is.na(estimanddb$`ISRCTN number (if available)`))
print("Position of missing values ")
which(is.na(estimanddb$`ISRCTN number (if available)`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

##################################################################################################################################

#Funding Type missing values:

print("Count of total missing values")
sum(is.na(estimanddb$`Funding type`))
print("Position of missing values ")
which(is.na(estimanddb$`Funding type`))

#[1] "Count of total missing values"
#[1] 27
#[1] "Position of missing values "
# [1] 1961 1963 1964 1965 1967 1970 1971 1983 1986 1987 1990 2000 2002 2006 2007 2009 2012 2014 2016 2018 2028 2034 2035 2041
#[25] 2043 2053 2060

table(estimanddb$'Funding type')

#    government organisation                       INDIV                    Industry                Not industry 
#                         62                           4                        1133                         825 
#private sector organisation 
#                         14 

estimanddb$`Funding type`[is.na(estimanddb$`Funding type`)] <- "Missing"

print("Count of total missing values")
sum(is.na(estimanddb$`Funding type`))
print("Position of missing values ")
which(is.na(estimanddb$`Funding type`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0

##################################################################################################################################

#Trial design missing values

print("Count of total missing values")
sum(is.na(estimanddb$`Trial design`))
print("Position of missing values ")
which(is.na(estimanddb$`Trial design`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

##################################################################################################################################

#Intervention type missing values

print("Count of total missing values")
sum(is.na(estimanddb$`Intervention type`))
print("Position of missing values ")
which(is.na(estimanddb$`Intervention type`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

##################################################################################################################################

#Protocol available missing values

print("Count of total missing values")
sum(is.na(estimanddb$`Protocol file available?`))
print("Position of missing values ")
which(is.na(estimanddb$`Protocol file available?`))

#[1] "Count of total missing values"
#[1] 263

#Large amount of 'Protocol available' values missing - double check with Morgaine how she would like me to proceed? May potentially need individual checking and entering.

##################################################################################################################################

#SAP available missing values

print("Count of total missing values")
sum(is.na(estimanddb$`SAP file available?`))
print("Position of missing values ")
which(is.na(estimanddb$`SAP file available?`))

#[1] "Count of total missing values"
#[1] 265

#Large amount of 'SAP available' values missing - double check with Morgaine how she would like me to proceed? May potentially need individual checking and entering.

##################################################################################################################################

#Trial phase missing values

print("Count of total missing values")
sum(is.na(estimanddb$`Trial Phase`))
print("Position of missing values ")
which(is.na(estimanddb$`Trial Phase`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

##################################################################################################################################

#Sponsor type missing values

print("Count of total missing values")
sum(is.na(estimanddb$`Sponsor type`))
print("Position of missing values ")
which(is.na(estimanddb$`Sponsor type`))

#[1] "Count of total missing values"
#[1] 1897

#Large amount of 'Sponsor type' values missing - double check with Morgaine how she would like me to proceed? May potentially need individual checking and entering.

#Checked with Morgaine - To categorise all missing values in 'Sponsor type' as "Missing" due to data not available from CTGOV registry.

estimanddb$`Sponsor type`[is.na(estimanddb$`Sponsor type`)] <- "Missing"

print("Count of total missing values")
sum(is.na(estimanddb$`Sponsor type`))
print("Position of missing values ")
which(is.na(estimanddb$`Sponsor type`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

#Save as xlsx file, enter Protocol & SAP information - re-upload for cleaning/encoding.

#'Protocol available' & 'SAP Available' values added to spreadsheet above - To be imported and if a value of "Combined" has been used in one field, the other should also be converted to "Combined".
#'

####################################################################################################################################

library(readxl)

estimanddb1 <- read_xlsx("Estimand_Sheet1.2.xlsx")

#Check 'Protocol Available' and 'SAP Available' missing values.

#Protocol available missing values

print("Count of total missing values")
sum(is.na(estimanddb1$`Protocol file available?`))
print("Position of missing values ")
which(is.na(estimanddb1$`Protocol file available?`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

print("Count of total missing values")
sum(is.na(estimanddb1$`SAP file available?`))
print("Position of missing values ")
which(is.na(estimanddb1$`SAP file available?`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

table(estimanddb1$`Protocol file available?`)

#Combined       No      Yes 
#     110       30     1925

table(estimanddb1$`SAP file available?`)

#Combined       No      Yes 
#     736      248     1081 

#NOTE: Amount of combined should be equal within BOTH 'Protocol Available' and 'SAP Available' fields.

```

#Protocol & SAP available:

```{r Data cleaning, include=TRUE}

#'Protocol Available' & 'SAP Available' fields

##NOTE: Amount of combined should be equal within BOTH 'Protocol Available' and 'SAP Available' fields.

estimanddb1$`Protocol file available?`[estimanddb1$`SAP file available?` == "Combined"] <- "Combined"

table(estimanddb1$`Protocol file available?`)

#Combined       No      Yes 
#     736       30     1299

table(estimanddb1$`SAP file available?`)

#Combined       No      Yes 
#     736      248     1081

#Check for missing:

print("Count of total missing values")
sum(is.na(estimanddb1$`Protocol file available?`))
print("Position of missing values ")
which(is.na(estimanddb1$`Protocol file available?`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

print("Count of total missing values")
sum(is.na(estimanddb1$`SAP file available?`))
print("Position of missing values ")
which(is.na(estimanddb1$`SAP file available?`))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)
```

#Funding type:

```{r Funding type field cleaning, include=TRUE}

table(estimanddb1$`Funding type`)

#    government organisation                       INDIV                    Industry                     Missing 
#                         62                           4                        1133                          27 
#               Not industry private sector organisation 
#                        825                          14 

estimanddb1$`Funding type`[estimanddb1$`Funding type` == "Not industry"] <- "Non-Industry"
estimanddb1$`Funding type`[estimanddb1$`Funding type` == "government organisation"] <- "Non-Industry"
estimanddb1$`Funding type`[estimanddb1$`Funding type` == "INDIV"] <- "Other"
estimanddb1$`Funding type`[estimanddb1$`Funding type` == "private sector organisation"] <- "Industry"

table(estimanddb1$`Funding type`)

#    Industry      Missing Non-Industry        Other 
#        1147           27          887            4

```

#Trial phase:

```{r Intervention type field cleaning, include=TRUE}

table(estimanddb1$`Trial Phase`)

# EARLY_PHASE1       Phase I    Phase I/II      Phase II  Phase II/III     Phase IIa     Phase III  Phase III/IV        PHASE1 
#           68            10             1            26             5             1            58             3           415 
#PHASE1|PHASE2        PHASE2 PHASE2|PHASE3        PHASE3 
#          160           760            77           481 

estimanddb1$`Trial Phase`[estimanddb1$`Trial Phase` == "EARLY_PHASE1"] <- "Phase I"
estimanddb1$`Trial Phase`[estimanddb1$`Trial Phase` == "PHASE1"] <- "Phase I"
estimanddb1$`Trial Phase`[estimanddb1$`Trial Phase` == "PHASE1|PHASE2"] <- "Phase I/II"
estimanddb1$`Trial Phase`[estimanddb1$`Trial Phase` == "PHASE2"] <- "Phase II"
estimanddb1$`Trial Phase`[estimanddb1$`Trial Phase` == "Phase IIa"] <- "Phase II"
estimanddb1$`Trial Phase`[estimanddb1$`Trial Phase` == "PHASE2|PHASE3"] <- "Phase II/III"
estimanddb1$`Trial Phase`[estimanddb1$`Trial Phase` == "PHASE3"] <- "Phase III"

table(estimanddb1$`Trial Phase`)

#     Phase I   Phase I/II     Phase II Phase II/III    Phase III Phase III/IV 
#         493          161          787           82          539            3 

```

# Sponsor type:

```{r Sponsor type field cleaning, include=TRUE}

table(estimanddb1$`Sponsor type`)

#To be re-labelled into "Industry" & "Non-Industry"

#                                        Charity                                      Government 
#                                              2                                               3 
#                      Hospital/treatment centre Hospital/treatment centre; University/education 
#                                             24                                               5 
#                                       Industry                  Industry; University/education 
#                                             66                                               1 
#                                        Missing                                              NK 
#                                           1897                                               2 
#                                   Not industry                                           Other 
#                                              9                                               1 
#                          Research organisation                            University/education 
#                                              1                                              54 

estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "Not industry"] <- "Non-Industry"
estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "Hospital/treatment centre"] <- "Non-Industry"
estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "Research organisation"] <- "Non-Industry"
estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "Charity"] <- "Non-Industry"
estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "Government"] <- "Non-Industry"
estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "Hospital/treatment centre; University/education"] <- "Non-Industry"
estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "University/education"] <- "Non-Industry"
estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "NK"] <- "Non-Industry"
estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "Other"] <- "Non-Industry"

table(estimanddb1$`Sponsor type`)

#                      Industry Industry; University/education                        Missing                   Non-Industry 
#                            66                              1                           1897                            101 

estimanddb1$`Sponsor type`[estimanddb1$`Sponsor type` == "Industry; University/education"] <- "Industry"

table(estimanddb1$`Sponsor type`)

#    Industry      Missing Non-Industry 
#          67         1897          101 

```

#Trial design:

```{r Trial design field cleaning, include=TRUE}

library(dplyr)
estimanddb1 %>% count(`Trial design`)

```

#Intervention type:

```{r Intervention type field cleaning, include=TRUE}

intervention_type <- estimanddb1 %>% count(`Intervention type`)

#####################################################################################################################################

estimanddb1$`Intervention type2` <- estimanddb1$`Intervention type`


estimanddb1 <- estimanddb1[order(estimanddb1$`Intervention type2`),]

#Replaced original values using MS Excel:

library(readxl)

newfields <- read_xlsx("Tr_Des&Int_Typ Fields.xlsx")

estimanddb2 <- cbind(estimanddb1,newfields)

###################################################################

table(estimanddb2$Int_typ_cat)

#      Behavioural       Combination            Device 
#               53                33                34 
#              IMP             Other Procedure/Surgery 
#             1878                14                30 
#       Supplement 
#               23 
               
#Check for missing

print("Count of total missing values")
sum(is.na(estimanddb2$Int_typ_cat))
print("Position of missing values ")
which(is.na(estimanddb2$Int_typ_cat))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)
```

#Trial Design: Allocation

```{r Trial design field cleaning, include=TRUE}

table(estimanddb2$Tr_Des_Allocat)

#1)                                                                                                                           equivalence trial 
#                                                                                                                                             1 
#                                                                                                                                            NA 
#                                                                                                                                           468 
#                                                                                                                                NON_RANDOMIZED 
#                                                                                                                                           191 
#Process of Care, Education or Self-Management, Psychological & Behavioural, Complex Intervention, #Physical, Management of Care, Rehabilitation 
#                                                                                                                                            1 
#                                                                                                                                    RANDOMIZED 
#                                                                                                                                          1305 
#                                                                                           Treatment, #Complex Intervention, Management of Care 
#                                                                                                                                             1 
#                                                                                                           Treatment, Dietary, Health Economic 
#                                                                                                                                             1 
#                                                         Treatment, Dietary, Imaging, Psychological & #Behavioural, Management of Care, Surgery 
#                                                                                                                                             1 
#                                                                                                                              Treatment, Drug 
#                                                                                                                                             1 
#                                                                                                                Treatment, Drug, Immunotherapy 
#                                                                                                                                             1 
#                                                                                                                            Treatment, Vaccine 
#                                                                                                                                             1 
#
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "RANDOMIZED"] <- "Randomised"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "NON_RANDOMIZED"] <- "Non-Randomised"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "NA"] <- "Missing"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "1) equivalence trial"] <- "Other"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "Process of Care, Education or Self-Management, Psychological & Behavioural, Complex Intervention, Physical, Management of Care, Rehabilitation"] <- "Other"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "Treatment, Complex Intervention, Management of Care"] <- "Other"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "Treatment, Dietary, Health Economic"] <- "Other"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "Treatment, Dietary, Imaging, Psychological & Behavioural, Management of Care, Surgery"] <- "Other"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "Treatment, Drug"] <- "Other"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "Treatment, Drug, Immunotherapy"] <- "Other"
estimanddb2$Tr_Des_Allocat[estimanddb2$Tr_Des_Allocat == "Treatment, Vaccine"] <- "Other"

table(estimanddb2$Tr_Des_Allocat)

#       Missing Non-Randomised          Other     Randomised 
#           468            191              8           1305

print("Count of total missing values")
sum(is.na(estimanddb2$Tr_Des_Allocat))
print("Position of missing values ")
which(is.na(estimanddb2$Tr_Des_Allocat))

#[1] "Count of total missing values"
#[1] 93

estimanddb2$Tr_Des_Allocat[is.na(estimanddb2$Tr_Des_Allocat)] <- "Missing"

print("Count of total missing values")
sum(is.na(estimanddb2$Tr_Des_Allocat))
print("Position of missing values ")
which(is.na(estimanddb2$Tr_Des_Allocat))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

table(estimanddb2$Tr_Des_Allocat)

#       Missing Non-Randomised          Other     Randomised 
#           561            191              8           1305 

```

#Trial Design: Intervention Model

```{r Trial Design Intervention Model, include=TRUE}

print("Count of total missing values")
sum(is.na(estimanddb2$Tr_Des_Int_Model))
print("Position of missing values ")
which(is.na(estimanddb2$Tr_Des_Int_Model))

#[1] "Count of total missing values"
#[1] 101

estimanddb2$Tr_Des_Int_Model[is.na(estimanddb2$Tr_Des_Int_Model)] <- "Missing"

print("Count of total missing values")
sum(is.na(estimanddb2$Tr_Des_Int_Model))
print("Position of missing values ")
which(is.na(estimanddb2$Tr_Des_Int_Model))

#[1] "Count of total missing values"
#[1] 0
#[1] "Position of missing values "
#integer(0)

table(estimanddb2$Tr_Des_Int_Model)

#   CROSSOVER    FACTORIAL      Missing     PARALLEL   SEQUENTIAL SINGLE_GROUP 
#         172           13          101         1150          157          472

estimanddb2$Tr_Des_Int_Model[estimanddb2$Tr_Des_Int_Model == "CROSSOVER"] <- "Crossover"
estimanddb2$Tr_Des_Int_Model[estimanddb2$Tr_Des_Int_Model == "FACTORIAL"] <- "Factorial"
estimanddb2$Tr_Des_Int_Model[estimanddb2$Tr_Des_Int_Model == "PARALLEL"] <- "Parallel"
estimanddb2$Tr_Des_Int_Model[estimanddb2$Tr_Des_Int_Model == "SEQUENTIAL"] <- "Sequential"
estimanddb2$Tr_Des_Int_Model[estimanddb2$Tr_Des_Int_Model == "SINGLE_GROUP"] <- "Single Group"

table(estimanddb2$Tr_Des_Int_Model)

#   Crossover    Factorial      Missing     Parallel   Sequential Single Group 
#         172           13          101         1150          157          472 

```

